### ISSUE TITLE
Выступление с DevOops 2022

### ISSUE THREAD

**Issue by ikurochkin** [evgeniy-kharchenko/The-Way-of-DevOps#3]
Привет, нашел твое выступление на DevOops про DevOps roadmap, может стоит добавить в документ в качестве ссылки? https://www.youtube.com/watch?v=72wxPffzNvk

**Comment by evgeniy-kharchenko** [comment]
Привет, лучше с DevOpsConf который будет, там будет более полная история, я добавил контента

**Comment by evgeniy-kharchenko** [comment]
Добавлно
